server:
  port: 8088
spring:
  application:
    name: hmdp
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hm-dianping?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.100.131
    port: 6379
    password: 182208
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 1
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.hmdp: debug
minio:
  access-key: minio
  secret-key: minio123
  bucket: redis
  endpoint: http://192.168.100.131:9000
  read-path: http://192.168.100.131:9000